---
- name: Install required packages
  package:
    name:
      - chrony
    state: present

- name: Disable timesyncd
  shell: timedatectl set-ntp no
  ignore_errors: yes
  tags:
    - notest

# configure chrony here
